[tool.black]
line-length = 80
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
)/
'''

[tool.flake8]
max-line-length = 80
max-doc-length = 200
extend-ignore = ["E501","E266"]
exclude = [".git", "__pycache__", "dist", "python/neo4j-python/*","software/leet-code/75/*"]
max-complexity = 10

[tool.isort]
atomic = true
profile = "black"
line_length = 80
skip_gitignore = true

[tool.pytest.ini_options]
norecursedirs = [
    "python/fastapi/backend/*",
    "python/fastapi/fastapi_template/*",
    "python/fastapi/fastapi_third/*",
    "python/neo4j-python/*",
    "python/pypi/reader-master/*",
]
