version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: fastapi_third:${FASTAPI_THIRD_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      FASTAPI_THIRD_HOST: 0.0.0.0
      FASTAPI_THIRD_DB_HOST: fastapi_third-db
      FASTAPI_THIRD_DB_PORT: 5432
      FASTAPI_THIRD_DB_USER: fastapi_third
      FASTAPI_THIRD_DB_PASS: fastapi_third
      FASTAPI_THIRD_DB_BASE: fastapi_third

  db:
    image: postgres:13.8-bullseye
    hostname: fastapi_third-db
    environment:
      POSTGRES_PASSWORD: "fastapi_third"
      POSTGRES_USER: "fastapi_third"
      POSTGRES_DB: "fastapi_third"
    volumes:
    - fastapi_third-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U fastapi_third
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: fastapi_third:${FASTAPI_THIRD_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      FASTAPI_THIRD_DB_HOST: fastapi_third-db
      FASTAPI_THIRD_DB_PORT: 5432
      FASTAPI_THIRD_DB_USER: fastapi_third
      FASTAPI_THIRD_DB_PASS: fastapi_third
      FASTAPI_THIRD_DB_BASE: fastapi_third
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "fastapi_third-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50



volumes:
  fastapi_third-db-data:
    name: fastapi_third-db-data
