default_context:
  project_name: 'fast_api_first'
  project_slug: 'fast_api_first'
  domain_main: 'fast_api_first.com'
  domain_staging: 'stag.fast_api_first.com'
  docker_swarm_stack_name_main: 'fast_api_first-com'
  docker_swarm_stack_name_staging: 'stag-fast_api_first-com'
  secret_key: '0879a4afad9d4611b6e0d49e3c9a4948c6a0e9cafbd446ea8571147726d58404'
  first_superuser: 'admin'
  first_superuser_password: 'BcO5'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fast_api_first.com", "https://stag.fast_api_first.com", "https://fast_api_first.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fast_api_first.com'
  postgres_password: 'R706s%3c"@lR'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'BcO5'
  traefik_constraint_tag: 'fast_api_first.com'
  traefik_constraint_tag_staging: 'stag.fast_api_first.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:BcO5'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
